Repository aeternity/state-channel-demo, pull requests merged in 2022-09, with the labels that each got.

#99 Feature/link to users aenalytics page
  client/src/components/game-screen/game-screen.vue
  client/src/components/header/header.vue
  client/src/components/transaction/transaction.test.ts
  client/src/components/transaction/transaction.vue
  client/src/stores/transactions.ts
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/sdk-service/sdk-service.ts
  client/tests/mocks.ts
  server/src/app.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.ts
  server/src/services/contract/contract.service.ts
Labels: enhancement, frontend

#100 feat: only save the last 5 rounds when reconnecting
  client/src/assets/svg/close.svg
  client/src/components/end-screen/end-screen.vue
  client/src/components/notification/notification.vue
  client/src/components/transaction-list/transaction-list.vue
  client/src/components/transaction-list/transactions-list.test.ts
  client/src/components/transaction/transaction.vue
  client/src/stores/transactions.ts
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/local-storage/local-storage.ts
Labels: enhancement, frontend

#101 fix: clear local storage on channel close
  client/src/utils/game-channel/game-channel.ts
Labels: bug, frontend

#104 revert: remove prepush testing
  .husky/pre-push
  client/package.json
  server/package.json
Labels: revert

#103 fix(client): remove reconnecting prefix showing on reload
  client/src/components/channel-initialization/channel-initialization.test.ts
  client/src/components/channel-initialization/channel-initialization.vue
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/utils/game-channel/game-channel.ts
Labels: bug

#107 feat: implement sharing results feature
  client/index.html
  client/package-lock.json
  client/src/app.vue
  client/src/assets/svg/facebook.svg
  client/src/assets/svg/linkedin.svg
  client/src/assets/svg/twitter.svg
  client/src/assets/svg/whatsapp.svg
  client/src/components/end-screen/end-screen.test.ts
  client/src/components/end-screen/end-screen.vue
  client/src/components/header/header.vue
  client/src/components/share-buttons/share-buttons.vue
  client/src/main.ts
  client/src/utils/game-channel/game-channel.ts
  server/src/services/bot/bot.service.ts
Labels: enhancement, frontend

#123 refactor(client): remove channel proxy
  client/src/utils/game-channel/game-channel.test.ts
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/sdk-service/sdk-service.test.ts
  client/tests/integration.test.ts
Labels: refactor

#124 refactor: decode contract events instead of decoding w compiler
  .env.dev-uat
  .github/workflows/dev-frontend.yml
  .github/workflows/prd-frontend.yml
  .github/workflows/stg-frontend.yml
  client/.env.testnet
  client/src/utils/game-channel/game-channel.test.ts
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/game-channel/game-channel.types.ts
  client/src/utils/sdk-service/sdk-service.test.ts
  server/src/env/.env.testnet.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.ts
  server/src/services/contract/contract.constants.ts
  server/src/services/contract/contract.service.spec.ts
  server/src/services/contract/contract.service.ts
  server/src/services/sdk/sdk.constants.ts
  server/src/services/sdk/sdk.interface.ts
  server/src/services/sdk/sdk.service.ts
Labels: refactor

#141 feat: seperate nodes per env config
  .env.dev
  .env.dev-uat
  .github/workflows/dev-backend.yml
  .github/workflows/dev-frontend.yml
  .github/workflows/prd-backend.yml
  .github/workflows/prd-frontend.yml
  .github/workflows/stg-backend.yml
  server/Dockerfile
  server/src/app.ts
  server/src/env/.env.production.ts
  server/src/env/index.ts
  server/src/services/sdk/sdk.constants.ts
Labels: enhancement

#143 feat: optimize performance
  client/package-lock.json
  client/package.json
  client/src/components/channel-initialization/channel-initialization.vue
  client/src/components/end-screen/end-screen.vue
  client/src/stores/transactions.ts
  client/src/utils/game-channel/game-channel.ts
  server/src/services/bot/bot.service.ts
Labels: bug, enhancement

#147 refactor: save results via transferFunds instead of sending an extra tx
  client/src/components/end-screen/end-screen.test.ts
  client/src/components/end-screen/end-screen.vue
  client/src/components/game-info/game-info.test.ts
  client/src/components/game-info/game-info.vue
  client/src/components/player-info/player-info.test.ts
  client/src/components/player-info/player-info.vue
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/sdk-service/sdk-service.ts
Labels: enhancement, refactor

#148 feat: add debug status endpoint
  docker-compose.yml
  server/src/route/route.spec.ts
  server/src/route/route.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.ts
  server/src/services/sdk/sdk.constants.ts
Labels: enhancement, backend

#163 refactor: drop usage of HTTP compiler
  client/src/utils/contract-bytecode/contract-bytecode.ts
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/sdk-service/sdk-service.test.ts
  client/src/utils/sdk-service/sdk-service.ts
  server/src/services/contract/contract.bytecode.ts
  server/src/services/contract/contract.service.spec.ts
  server/src/services/contract/contract.service.ts
  server/src/services/sdk/sdk.service.ts
  server/test/utils.ts
Labels: refactor

#164 feat: handle running out of coins
  client/src/components/end-screen/end-screen.vue
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/utils/game-channel/game-channel.ts
  server/src/route/route.spec.ts
  server/src/services/bot/bot.constants.ts
Labels: frontend

#165 fix: handle tx log unable to be sent
  client/src/utils/game-channel/game-channel.ts
  server/src/route/route.spec.ts
  server/src/services/bot/bot.service.ts
  server/test/interfaces.ts
  server/test/mocks.ts
Labels: bug

#156 Feat/re implement mobile
  client/src/app.vue
  client/src/assets/svg/facebook.svg
  client/src/assets/svg/linkedin.svg
  client/src/assets/svg/twitter.svg
  client/src/assets/svg/whatsapp.svg
  client/src/components/channel-initialization/channel-initialization.vue
  client/src/components/game-info/game-info.vue
  client/src/components/game-screen/game-screen.vue
  client/src/components/generic-button/generic-button.vue
  client/src/components/header/header.vue
  client/src/components/loading-animation/loading-animation.vue
  client/src/components/notification/notification.vue
  client/src/components/player-info/player-info.vue
  client/src/components/rock-paper-scissors/rock-paper-scissors.test.ts
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/components/selection-icon/selection-icon.vue
  client/src/components/share-buttons/share-buttons.vue
  client/src/components/transaction-list/transaction-list.vue
  client/src/stores/is-on-mobile.ts
Labels: enhancement, frontend

#179 chore: maintain node logs
  .gitignore
  docker-compose.yml
  server/src/services/sdk/sdk.service.ts
Labels: chore
