Repository aeternity/state-channel-demo, pull requests merged in 2022-10, with the labels that each got.

#180 fix: handle channel timeout
  .github/workflows/prd-backend.yml
  .github/workflows/prd-frontend.yml
  server/src/services/bot/bot.service.ts
Labels: bug, backend

#160 replace runningSince to timeStamp
  server/src/route/route.spec.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.ts
Labels: Hacktoberfest-accepted

#204 feat: start new round after 3 seconds and implement new game design
  client/index.html
  client/src/css/game-screen/game-screen.css
  client/src/css/game-screen/game-screen.scss
  client/src/css/header/header.css
  client/src/css/header/header.scss
  client/src/css/styles.css
  client/src/css/styles.scss
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/game-channel/game-channel.middleware.js
Labels: enhancement, frontend

#102 docs: provide docs for channel usage
  CHANNEL_USAGE.md
  README.md
Labels: documentation

#206 fix(client): use contractSource in client for vite build
  client/src/js/contract-bytecode/contract-bytecode.js
  client/src/js/contract/contract.js
  client/src/js/game-channel/game-channel.js
  client/src/js/sdk-service/sdk-service.js
  client/vite.config.js
Labels: frontend

#213 feat: render logs in new terminal
  client/index.html
  client/main.js
  client/src/css/header/header.css
  client/src/css/header/header.scss
  client/src/css/notification/notification.css
  client/src/css/notification/notification.scss
  client/src/css/styles.css
  client/src/css/styles.scss
  client/src/css/transactions/transactions.css
  client/src/css/transactions/transactions.scss
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/game-channel/game-channel.js
  client/src/js/game-channel/game-channel.middleware.js
  client/src/js/sdk-service/sdk-service.js
  client/src/js/terminal/terminal.js
  client/src/js/utils/utils.js
  client/src/types/index.d.ts
  server/src/services/bot/bot.service.ts
  server/src/services/contract/contract.service.ts
Labels: frontend

#215 feat: add allow user to end game
  client/index.html
  client/main.js
  client/src/css/end-screen/end-screen.css
  client/src/css/end-screen/end-screen.scss
  client/src/css/header/header.css
  client/src/css/header/header.scss
  client/src/css/styles.css
  client/src/css/styles.scss
  client/src/css/transactions/transactions.css
  client/src/css/transactions/transactions.scss
  client/src/js/autoplay/autoplay-btn.controler.js
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/dom-manipulation/end-screen.js
  client/src/js/game-channel/game-channel.js
  client/src/js/game-channel/game-channel.middleware.js
  client/src/js/local-storage/local-storage.js
  client/src/js/sdk-service/sdk-service.js
  client/src/js/utils/utils.js
  client/src/types/index.d.ts
Labels: enhancement, frontend

#223 fix: responsiveness of terminal
  client/main.js
  client/src/css/end-screen/end-screen.css
  client/src/css/end-screen/end-screen.scss
  client/src/css/game-screen/game-screen.css
  client/src/css/game-screen/game-screen.scss
  client/src/css/rock-paper-scissors/rock-paper-scissors.css
  client/src/css/rock-paper-scissors/rock-paper-scissors.scss
  client/src/css/styles.css
  client/src/css/transactions/transactions.css
  client/src/css/transactions/transactions.scss
  client/src/tests/e2e.js
Labels: enhancement, frontend

#225 feat: add start over button
  client/src/css/header/header.css
  client/src/css/header/header.scss
  client/src/css/styles.css
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/tests/e2e.js
Labels: enhancement, frontend

#228 feat: improve design for wide-screen monitors and remove expanding terminal
  client/index.html
  client/src/assets/images/minimize.png
  client/src/assets/svg/expand.svg
  client/src/css/game-screen/game-screen.css
  client/src/css/header/header.css
  client/src/css/header/header.scss
  client/src/css/rock-paper-scissors/rock-paper-scissors.css
  client/src/css/rock-paper-scissors/rock-paper-scissors.scss
  client/src/css/styles.css
  client/src/css/styles.scss
  client/src/css/transactions/transactions.css
  client/src/css/transactions/transactions.scss
  client/src/js/dom-manipulation/dom-manipulation.js
Labels: enhancement, frontend

#229 feat: remove reset app functionality from logo
  client/index.html
  client/src/css/header/header.css
  client/src/css/header/header.scss
  client/src/css/styles.css
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/game-channel/game-channel.middleware.js
Labels: frontend

#232 feat: display winner in terminal
  client/src/css/styles.css
  client/src/css/transactions/transactions.css
  client/src/css/transactions/transactions.scss
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/dom-manipulation/end-screen.js
  client/src/js/game-channel/game-channel.js
  client/src/js/sdk-service/sdk-service.js
  client/src/js/terminal/terminal.js
  client/src/js/utils/utils.js
  client/src/tests/e2e.js
  client/src/types/index.d.ts
Labels: enhancement, frontend

#233 feat: display user and bot addresses and link to explorer
  client/index.html
  client/src/css/game-screen/game-screen.css
  client/src/css/game-screen/game-screen.scss
  client/src/css/styles.css
  client/src/css/styles.scss
  client/src/css/transactions/transactions.css
  client/src/css/transactions/transactions.scss
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/game-channel/game-channel.middleware.js
  client/src/js/utils/utils.js
Labels: enhancement, frontend

#234 refactor: instead of dialogs, show text as error logs
  client/src/js/game-channel/game-channel.js
  client/src/js/local-storage/local-storage.js
Labels: enhancement, frontend
