Repository aeternity/state-channel-demo, pull requests merged in 2022-06, with the labels that each got.

#7 feat: initialize server
  .gitignore
  docker-compose.yml
  nodejs/.eslintrc.js
  nodejs/.gitignore
  nodejs/.mocharc.json
  nodejs/Dockerfile
  nodejs/package-lock.json
  nodejs/package.json
  nodejs/src/index.ts
  nodejs/src/services/bot/bot.service.ts
  nodejs/src/services/sdk/sdk.service.development.ts
  nodejs/src/services/sdk/sdk.service.ts
  nodejs/tsconfig.json
Labels: chore, backend

#6 feat: configure eslint, prettier and vitest
  front/package-lock.json
  front/package.json
  front/src/components/HelloWorld.vue
  front/src/main.ts
  front/vite.config.ts
  vuejs/.eslintrc.js
  vuejs/.gitignore
  vuejs/.prettierignore
  vuejs/.prettierrc
  vuejs/README.md
  vuejs/index.html
  vuejs/package-lock.json
  vuejs/package.json
  vuejs/public/favicon.ico
  vuejs/src/App.vue
  vuejs/src/assets/logo.png
  vuejs/src/components/HelloWorld.vue
  vuejs/src/env.d.ts
  vuejs/src/main.ts
  vuejs/tests/basic.test.ts
  vuejs/tsconfig.json
  vuejs/tsconfig.node.json
  vuejs/vite.config.ts
Labels: chore, frontend

#8 feat: Run all apps through docker
  README.md
  docker-compose.yml
  vuejs/Dockerfile
  vuejs/package.json
  vuejs/vite.config.ts
Labels: chore

#14 feat: initialize channel connection and connect to ws
  docker-compose.yml
  vuejs/.eslintrc.js
  vuejs/package-lock.json
  vuejs/package.json
  vuejs/src/App.vue
  vuejs/src/components/ChannelInitialization.vue
  vuejs/src/components/HelloWorld.vue
  vuejs/src/sdk/sdk.ts
  vuejs/tests/basic.test.ts
  vuejs/tsconfig.json
  vuejs/vite.config.ts
Labels: frontend

#15 Funding through faucet
  .env.dev
  .gitignore
  README.md
  docker-compose.yml
  nodejs/.eslintrc.js
  nodejs/package-lock.json
  nodejs/package.json
  nodejs/src/index.ts
  nodejs/src/services/bot/bot.service.ts
  nodejs/src/services/sdk/sdk.service.constants.ts
  nodejs/src/services/sdk/sdk.service.development.ts
  nodejs/src/services/sdk/sdk.service.ts
  vuejs/src/components/ChannelInitialization.vue
  vuejs/src/sdk/sdk.ts
Labels: enhancement, backend
