Repository aeternity/state-channel-demo, pull requests merged in 2022-07, with the labels that each got.

#19 Feature/add logger
  nodejs/package-lock.json
  nodejs/package.json
  nodejs/src/app.ts
  nodejs/src/index.ts
  nodejs/src/logger.ts
  nodejs/src/route/index.ts
  nodejs/src/route/route.interface.ts
  nodejs/src/route/route.spec.ts
  nodejs/src/route/route.ts
  nodejs/src/services/bot/bot.service.ts
  nodejs/src/services/bot/index.ts
  nodejs/src/services/sdk/index.ts
  nodejs/src/services/sdk/sdk.service.constants.ts
  nodejs/src/services/sdk/sdk.service.ts
  nodejs/src/tests/index.ts
  nodejs/src/tests/tests.interface.ts
  nodejs/src/tests/tests.mocks.ts
Labels: chore, backend

#21 refactor: rename core folders to server client
  .husky/pre-commit
  .husky/pre-push
  README.md
  client/.eslintrc.js
  client/.gitignore
  client/.prettierignore
  client/.prettierrc
  client/Dockerfile
  client/README.md
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/src/App.vue
  client/src/assets/logo.png
  client/src/components/ChannelInitialization.vue
  client/src/env.d.ts
  client/src/main.ts
  client/src/sdk/sdk.ts
  client/tests/basic.test.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  commitlint.config.js
  docker-compose.yml
  server/.eslintrc.js
  server/.gitignore
  server/Dockerfile
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/index.ts
  server/src/logger.ts
  server/src/route/index.ts
  server/src/route/route.interface.ts
  server/src/route/route.spec.ts
  server/src/route/route.ts
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
  server/src/services/bot/index.ts
  server/src/services/sdk/index.ts
  server/src/services/sdk/sdk.service.constants.ts
  server/src/services/sdk/sdk.service.ts
  server/src/tests/index.ts
  server/src/tests/tests.interface.ts
  server/src/tests/tests.mocks.ts
  server/tsconfig.json
Labels: chore

#22 Feature/implement open state channel button
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/components/ChannelInitialization.vue
  client/src/components/GenericButton.vue
  client/src/sdk/sdk.ts
  client/tests/basic.test.ts
  client/tests/channel-initialization.test.ts
  client/tests/sdk.test.ts
  client/vite.config.ts
Labels: frontend

#24 feat: bot should send its balance back to the faucet on channel termination
  .env.dev
  .env.dev-uat
  client/src/components/ChannelInitialization.vue
  docker-compose.yml
  server/jest.config.js
  server/package.json
  server/src/route/route.spec.ts
  server/src/route/route.ts
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
  server/src/services/bot/index.ts
  server/src/services/sdk/sdk.service.constants.ts
  server/src/services/sdk/sdk.service.ts
  server/src/tests/index.ts
  server/test/index.ts
  server/test/integration/bot.service.spec.ts
  server/test/interfaces.ts
  server/test/mocks.ts
  server/test/utils.ts
Labels: enhancement, backend

#25 feat: user returns his remaining coins to the faucet
  .env.dev
  client/src/components/ChannelInitialization.vue
  client/src/sdk/sdk.ts
  client/tests/sdk.test.ts
  client/vite.config.ts
  docker-compose.yml
Labels: enhancement, frontend

#35 feat: retry funding request when response error code is different than 425
  .github/workflows/dev-backend.yml
  .github/workflows/dev-frontend.yml
  .github/workflows/prd-frontend.yml
  .github/workflows/stg-frontend.yml
  server/package.json
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
Labels: bug, backend

#36 Feature/rock paper scissor components
  client/src/App.vue
  client/src/components/GenericButton.vue
  client/src/components/Header.vue
  client/src/components/PopUp.vue
  client/src/components/RockPaperScissor.vue
  client/src/stores/game.ts
  client/src/stores/popup.ts
  client/tests/channel-initialization.test.ts
  client/tests/popup.test.ts
  client/tests/rock-paper-scissor.test.ts
Labels: frontend

#37 feat: add loader
  client/src/components/ChannelInitialization.vue
  client/src/components/GenericButton.vue
  client/src/components/LoadingAnimation.vue
  client/src/components/PopUp.vue
  client/src/components/TransactionsList.vue
  client/tests/channel-initialization.test.ts
Labels: frontend

#40 refactor: move channel instance to App component
  client/src/App.vue
  client/src/components/ChannelInitialization.vue
  client/src/sdk/sdk.ts
  client/src/sdk/sdkService.ts
  client/src/stores/channel.ts
  client/tests/channel-initialization.test.ts
  client/tests/sdk.test.ts
Labels: bug, frontend

#41 Refactor/update client architecture
  client/src/App.vue
  client/src/components/ChannelInitialization.vue
  client/src/components/Header.vue
  client/src/components/PlayerInfo.vue
  client/src/components/TransactionsList.vue
  client/src/sdk/GameChannel.ts
  client/src/sdk/sdk.ts
  client/src/sdk/sdkService.ts
  client/src/stores/channel.ts
  client/tests/channel-initialization.test.ts
  client/tests/player-info.test.ts
  client/tests/sdk.test.ts
  client/tests/transactions-list.test.ts
  server/src/services/bot/bot.service.ts
Labels: refactor

#43 Performance: simplify server sdk
  server/.eslintrc.js
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
  server/src/services/sdk/index.ts
  server/src/services/sdk/sdk.constants.ts
  server/src/services/sdk/sdk.service.ts
  server/test/integration/bot.service.spec.ts
  server/test/utils.ts
Labels: refactor

#49 feature: deploy game contract in channel
  .github/workflows/dev-backend.yml
  .github/workflows/dev-frontend.yml
  .github/workflows/prd-backend.yml
  .github/workflows/prd-frontend.yml
  .github/workflows/stg-backend.yml
  .github/workflows/stg-frontend.yml
  client/.dockerignore
  client/Dockerfile
  client/package-lock.json
  client/package.json
  client/src/components/GameInfo.vue
  client/src/components/Header.vue
  client/src/components/PlayerInfo.vue
  client/src/sdk/GameChannel.ts
  client/src/sdk/sdkService.ts
  client/tests/game-info.test.ts
  client/tests/player-info.test.ts
  client/tests/sdk.test.ts
  client/vite.config.ts
  docker-compose.yml
  server/.dockerignore
  server/.eslintrc.js
  server/Dockerfile
  server/package-lock.json
  server/package.json
  server/src/route/route.spec.ts
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
  server/src/services/sdk/sdk.constants.ts
  server/src/services/sdk/sdk.service.ts
  server/test/integration/bot.service.spec.ts
  server/test/mocks.ts
  server/test/utils.ts
Labels: enhancement, backend, frontend

#50 feat: create user selection transaction
  client/.prettierignore
  client/src/App.vue
  client/src/components/ChannelInitialization.vue
  client/src/components/RockPaperScissors.vue
  client/src/game/GameManager.ts
  client/src/sdk/GameChannel.ts
  client/src/sdk/sdkService.ts
  client/src/stores/game.ts
  client/tests/game-manager.test.ts
  client/tests/mocks.ts
  client/tests/rock-paper-scissor.test.ts
  client/tests/sdk.test.ts
  client/tests/utils.ts
Labels: frontend

#57 fix: fix server hangup and error message showing when retrying
  client/src/components/ChannelInitialization.vue
  client/src/sdk/GameChannel.ts
  client/tests/channel-initialization.test.ts
  client/tests/sdk.test.ts
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
  server/test/integration/bot.service.spec.ts
Labels: bug

#60 feat: update terminal design
  client/src/assets/minimize.png
  client/src/assets/svg/autoplay.svg
  client/src/assets/svg/expand.svg
  client/src/components/TransactionsList.vue
  client/src/stores/transactions.ts
  client/tests/transactions-list.test.ts
Labels: frontend

#55 Feature: Add contract service - respond to player move
  docker-compose.yml
  server/.eslintrc.js
  server/src/route/route.spec.ts
  server/src/services/bot/bot.constants.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
  server/src/services/bot/index.ts
  server/src/services/contract/contract.constants.ts
  server/src/services/contract/contract.interface.ts
  server/src/services/contract/contract.service.spec.ts
  server/src/services/contract/contract.service.ts
  server/src/services/contract/index.ts
  server/src/services/sdk/index.ts
  server/src/services/sdk/sdk.constants.ts
  server/src/services/sdk/sdk.interface.ts
  server/src/services/sdk/sdk.service.spec.ts
  server/src/services/sdk/sdk.service.ts
  server/test/integration/bot.service.spec.ts
  server/test/utils.ts
Labels: backend

#61 feat(popup): add tooltip
  client/.eslintrc.js
  client/src/assets/svg/info.svg
  client/src/assets/svg/rectangle.svg
  client/src/components/Header.vue
  client/src/components/PopUp.vue
  client/src/components/Tooltip.vue
  client/src/stores/popup.ts
  client/tests/popup.test.ts
Labels: frontend
