Repository aeternity/state-channel-demo, pull requests merged in 2022-11, with the labels that each got.

#236 Feat/validate contract call before signing
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/game-channel/game-channel.js
  server/src/services/bot/bot.service.ts
  server/src/services/contract/contract.service.spec.ts
  server/src/services/contract/contract.service.ts
Labels: enhancement

#237 fix: balances not showing on some resolutions
  client/src/css/styles.css
  client/src/css/styles.scss
Labels: frontend

#240 feat: allow user to start over after timeouts
  .github/workflows/dev-frontend.yml
  .github/workflows/stg-frontend.yml
  client/.env.testnet
  client/src/js/dom-manipulation/dom-manipulation.js
  client/src/js/game-channel/game-channel.js
  server/src/env/.env.testnet.ts
Labels: enhancement, frontend

#246 feat(server): add an authenticated endpoint to cleanup stats
  server/jest.config.js
  server/src/route/route.spec.ts
  server/src/route/route.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.ts
Labels: backend
