Repository aeternity/state-channel-demo, pull requests merged in 2022-08, with the labels that each got.

#66 Add jsdoc for server
  docker-compose.yml
  server/package-lock.json
  server/package.json
  server/src/route/route.interface.ts
  server/src/services/bot/bot.constants.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.spec.ts
  server/src/services/bot/bot.service.ts
  server/src/services/contract/contract.service.spec.ts
  server/src/services/contract/contract.service.ts
  server/src/services/sdk/sdk.constants.ts
  server/src/services/sdk/sdk.interface.ts
  server/src/services/sdk/sdk.service.ts
  server/test/integration/bot.service.spec.ts
  server/test/utils.ts
Labels: chore, backend

#69 refactor(client): remove sdk proxy
  client/src/App.vue
  client/src/sdk/GameChannel.ts
  client/src/sdk/sdkService.ts
  client/tests/game-manager.test.ts
  client/tests/sdk.test.ts
Labels: enhancement, refactor

#75 refactor: remove popup
  client/src/App.vue
  client/src/components/PopUp.vue
  client/src/sdk/GameChannel.ts
  client/src/stores/popup.ts
  client/tests/popup.test.ts
  client/tests/sdk.test.ts
Labels: frontend

#76 fix(ci): use the correct backend url on stg env
  .github/workflows/stg-frontend.yml
Labels: bug

#77 Refactor/client
  client/.eslintrc.js
  client/src/app.vue
  client/src/components/channel-initialization/channel-initialization.test.ts
  client/src/components/channel-initialization/channel-initialization.vue
  client/src/components/game-info/game-info.test.ts
  client/src/components/game-info/game-info.vue
  client/src/components/generic-button/generic-button.vue
  client/src/components/header/header.vue
  client/src/components/loading-animation/loading-animation.vue
  client/src/components/player-info/player-info.test.ts
  client/src/components/player-info/player-info.vue
  client/src/components/rock-paper-scissors/rock-paper-scissor.test.ts
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/components/tooltip/tooltip.vue
  client/src/components/transaction-list/transaction-list.vue
  client/src/components/transaction-list/transactions-list.test.ts
  client/src/components/transaction/transaction.test.ts
  client/src/components/transaction/transaction.vue
  client/src/main.ts
  client/src/stores/channel.ts
  client/src/stores/transactions.ts
  client/src/utils/game-channel/game-channel.test.ts
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/sdk-service/sdk-service.test.ts
  client/src/utils/sdk-service/sdk-service.ts
  client/vite.config.ts
Labels: refactor

#80 feat: process end-game tx and show ending screen
  client/src/app.vue
  client/src/components/end-screen/end-screen.test.ts
  client/src/components/end-screen/end-screen.vue
  client/src/components/generic-button/generic-button.vue
  client/src/components/header/header.vue
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/components/transaction-list/transaction-list.vue
  client/src/components/transaction-list/transactions-list.test.ts
  client/src/components/transaction/transaction.test.ts
  client/src/components/transaction/transaction.vue
  client/src/utils/game-channel/game-channel.ts
  server/src/services/bot/bot.service.ts
Labels: frontend

#81 Group transaction logs
  client/src/components/accordion/accordion.vue
  client/src/components/end-screen/end-screen.vue
  client/src/components/transaction-list/transaction-list.vue
  client/src/components/transaction-list/transactions-list.test.ts
  client/src/components/transaction/transaction.test.ts
  client/src/components/transaction/transaction.vue
  client/src/stores/transactions.ts
  client/src/utils/game-channel/game-channel.ts
Labels: frontend

#82 feat: clicking logo on end-screen resets app
  client/src/components/header/header.vue
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/main.ts
Labels: enhancement, frontend

#85 feat: add shadow to landing page
  client/src/app.vue
  client/src/components/channel-initialization/channel-initialization.vue
Labels: frontend

#87 feat: update autoplay results
  client/src/components/end-screen/end-screen.test.ts
  client/src/components/end-screen/end-screen.vue
  client/src/components/transaction-list/transactions-list.test.ts
  client/src/utils/game-channel/game-channel.ts
  client/tests/mocks.ts
Labels: enhancement, frontend

#86 feat: replace text with icons
  client/src/app.vue
  client/src/assets/images/logo.png
  client/src/assets/images/minimize.png
  client/src/assets/images/paper.png
  client/src/assets/images/rock.png
  client/src/assets/images/scissors.png
  client/src/components/end-screen/end-screen.vue
  client/src/components/header/header.vue
  client/src/components/rock-paper-scissors/rock-paper-scissor.test.ts
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/components/selection-icon/selection-icon.vue
  client/src/components/transaction-list/transaction-list.vue
Labels: enhancement, frontend

#91 feat(server): add cors
  .gitignore
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/sdk-service/sdk-service.ts
  server/src/app.ts
Labels: bug, enhancement, backend

#92 Change wording for signed transaction
  client/src/components/transaction/transaction.test.ts
  client/src/components/transaction/transaction.vue
  client/src/utils/game-channel/game-channel.ts
  client/src/utils/game-channel/game-channel.types.ts
  client/tests/mocks.ts
  server/src/services/bot/bot.interface.ts
  server/src/services/bot/bot.service.ts
  server/src/services/contract/contract.service.ts
Labels: enhancement, frontend

#93 feat: split game screen in two
  client/src/app.vue
  client/src/components/accordion/accordion.vue
  client/src/components/end-screen/end-screen.vue
  client/src/components/game-info/game-info.vue
  client/src/components/game-screen/game-screen.vue
  client/src/components/header/header.vue
  client/src/components/player-info/player-info.vue
  client/src/components/rock-paper-scissors/rock-paper-scissors.test.ts
  client/src/components/rock-paper-scissors/rock-paper-scissors.vue
  client/src/components/selection-icon/selection-icon.vue
  client/src/components/transaction-list/transaction-list.vue
  client/src/utils/game-channel/game-channel.ts
Labels: enhancement, frontend
